### ISSUE TITLE
BUG:  custom_components/wattbox/__init__.py (ERROR) 

### ISSUE THREAD

**Issue by garyak** [eseglem/hass-wattbox#1]
Upgraded to 94.3 from 93.2 and got this error:
```
 Error during setup of component wattbox 
 9:18 AM custom_components/wattbox/__init__.py (ERROR) 
```
Intel NUC, Ubuntu 18.04.2 LTS, Hassio install, Hass.io supervisor 166.

From ha-log:

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 153, in _async_setup_component
    hass, processed_config)
  File "/config/custom_components/wattbox/__init__.py", line 69, in async_setup
    from pywattbox import WattBox
ModuleNotFoundError: No module named 'pywattbox'
```

**Comment by eseglem** [comment]
Legacy issue.
