### ISSUE TITLE
Unable to import component: No module named 'pywattbox.base'

### ISSUE THREAD

**Issue by garyak** [eseglem/hass-wattbox#17]
## Version of the custom_component

v0.9.0b1
## Configuration
wattbox:
- host: !secret wattbox1_ip
  username: !secret it_user
  password: !secret it_psswd
  name: wattbox1
  resources:
    - current_value
    - power_value
    - voltage_value
- host: !secret wattbox2_ip
  username: !secret it_user
  password: !secret it_psswd
  name: wattbox2
  resources:
    - current_value
    - power_value
    - voltage_value

HA Log Error
```
2023-11-15 14:47:43.778 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration wattbox: Unable to import component: No module named 'pywattbox.base'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 215, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 816, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/wattbox/__init__.py", line 28, in <module>
    from pywattbox.base import BaseWattBox
ModuleNotFoundError: No module named 'pywattbox.base'
```

## Describe the bug
Invalid config
The following integrations and platforms could not be set up:
## Debug log

```text

Unable to restart due to bad config

```

**Comment by eseglem** [comment]
Forgot I was still pointing it at GitHub directly and the dependency is a bit funky because of that. I'll try to push a new release of pywattbox and point at it instead tomorrow. If you pip install the requirements.txt manually, it should work in the meantime.

**Comment by eseglem** [comment]
Hopefully v0.9.0b2 fixes this. Should be up. I'll try and test it more later as well.

**Comment by eseglem** [comment]
Actually had a few more issues with dependencies, and mine not wanting to build stuff. Think I got past that all now. 

Latest is now v0.9.0b5

**Comment by garyak** [comment]
9.0b5 started. No errors. I'll check it out in more detail over the next few days. Entity names didn't seem to change. Customization worked without edits.
