### ISSUE TITLE
Voltage/Current Sensors Reading Zero

### ISSUE THREAD

**Issue by kernelpanic85** [eseglem/hass-wattbox#21]
## Version of the custom_component
0.8.2

## Configuration

```
wattbox:
- host: 192.168.2.62
  name: Theater-PDU
  username: !secret wattbox_user
  password: !secret wattbox_pw
  scan_interval: 00:00:10
```

## Describe the bug
The voltage and current sensors read zero for my WB-800VPS-IPVM-12. Is it possible to fix or add support for this model? It seems to use [this API](https://www.snapav.com/wcsstore/ExtendedSitesCatalogAssetStore/attachments/documents/PowerManagement/ProtocolsAndDrivers/SnapAV_Wattbox_API_V2.4.pdf)

![image](https://github.com/eseglem/hass-wattbox/assets/80057019/66eda67f-e275-47b7-8019-ccb10e93b0e7)

## Debug log

```
2024-04-10 11:18:29.836 DEBUG (MainThread) [custom_components.wattbox] Updated:  (http://192.168.2.62:80): None - <pywattbox.wattbox.WattBox object at 0x5c9dc3d8>
2024-04-10 11:18:39.820 DEBUG (MainThread) [custom_components.wattbox] Updated:  (http://192.168.2.62:80): None - <pywattbox.wattbox.WattBox object at 0x5c9dc3d8>
2024-04-10 11:18:49.824 DEBUG (MainThread) [custom_components.wattbox] Updated:  (http://192.168.2.62:80): None - <pywattbox.wattbox.WattBox object at 0x5c9dc3d8>
2024-04-10 11:18:59.830 DEBUG (MainThread) [custom_components.wattbox] Updated:  (http://192.168.2.62:80): None - <pywattbox.wattbox.WattBox object at 0x5c9dc3d8>
2024-04-10 11:19:09.827 DEBUG (MainThread) [custom_components.wattbox] Updated:  (http://192.168.2.62:80): None - <pywattbox.wattbox.WattBox object at 0x5c9dc3d8>
2024-04-10 11:19:19.826 DEBUG (MainThread) [custom_components.wattbox] Updated:  (http://192.168.2.62:80): None - <pywattbox.wattbox.WattBox object at 0x5c9dc3d8>
2024-04-10 11:19:29.840 DEBUG (MainThread) [custom_components.wattbox] Updated:  (http://192.168.2.62:80): None - <pywattbox.wattbox.WattBox object at 0x5c9dc3d8>
```

**Comment by kernelpanic85** [comment]
Update: I found the HA community thread and updated to 0.9.5b5 and I see this in the logs now:

```
2024-04-10 12:23:52.394 ERROR (MainThread) [homeassistant.setup] Error during setup of component wattbox
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/setup.py", line 390, in _async_setup_component
result = await task
^^^^^^^^^^
File "/config/custom_components/wattbox/__init__.py", line 106, in async_setup
wattbox = await async_create_http_wattbox(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/pywattbox/http_wattbox.py", line 223, in async_create_http_wattbox
return await _async_create_wattbox(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/pywattbox/base.py", line 110, in _async_create_wattbox
await wattbox.async_get_initial()
File "/usr/local/lib/python3.12/site-packages/pywattbox/http_wattbox.py", line 39, in async_get_initial
response.raise_for_status()
File "/usr/local/lib/python3.12/site-packages/httpx/_models.py", line 761, in raise_for_status
raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '401 Unauthorized' for url 'http://192.168.2.62/wattbox_info.xml'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401
```

**Comment by sheyman1** [comment]
Similar or same issue for me.

2024-07-31 00:22:35.921 WARNING (ImportExecutor_0) [homeassistant.const] ELECTRIC_POTENTIAL_VOLT was used from wattbox, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfElectricPotential.VOLT instead, please report it to the author of the 'wattbox' custom integration
2024-07-31 00:22:35.923 WARNING (ImportExecutor_0) [homeassistant.const] POWER_WATT was used from wattbox, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfPower.WATT instead, please report it to the author of the 'wattbox' custom integration
2024-07-31 00:22:35.924 WARNING (ImportExecutor_0) [homeassistant.const] TIME_MINUTES was used from wattbox, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTime.MINUTES instead, please report it to the author of the 'wattbox' custom integration
2024-07-31 00:22:35.926 INFO (MainThread) [homeassistant.setup] Setting up wattbox
2024-07-31 00:22:35.926 INFO (MainThread) [custom_components.wattbox]
-------------------------------------------------------------------
wattbox
Version: 0.9.0

**Comment by zacs** [comment]
I have only had this component for a couple weeks, but I've never had any sensor created for power, voltage, and current. I'm running HA 2024.10.1 and component 0.9.0b5. 

It looks like it has been address in PR #22 by @aleksrozman in case anyone wants to cherry pick that into HACS.

**Comment by kernelpanic85** [comment]
Thanks for the follow up! I tried port 22 on v 0.8.2 and got the following error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 716, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 468, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 463, in _make_request
    httplib_response = conn.getresponse()
                       ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 1428, in getresponse
    response.begin()
  File "/usr/local/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 313, in _read_status
    raise BadStatusLine(line)
http.client.BadStatusLine: SSH-2.0-dropbear_2020.81


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 802, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/util/retry.py", line 552, in increment
    raise six.reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 716, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 468, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 463, in _make_request
    httplib_response = conn.getresponse()
                       ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 1428, in getresponse
    response.begin()
  File "/usr/local/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 313, in _read_status
    raise BadStatusLine(line)
urllib3.exceptions.ProtocolError: ('Connection aborted.', BadStatusLine('SSH-2.0-dropbear_2020.81\r\n'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 416, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/wattbox/__init__.py", line 97, in async_setup
    hass.data[DOMAIN_DATA][name] = await hass.async_add_executor_job(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pywattbox/wattbox.py", line 56, in __init__
    result = requests.get(
             ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/adapters.py", line 682, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine('SSH-2.0-dropbear_2020.81\r\n'))
```

Port 22 on v0.9.0b5 gave this:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/scrapli/transport/plugins/asyncssh/transport.py", line 195, in open
    self.session = await asyncio.wait_for(
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/tasks.py", line 520, in wait_for
    return await fut
           ^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/asyncssh/connection.py", line 8865, in connect
    return await asyncio.wait_for(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/tasks.py", line 520, in wait_for
    return await fut
           ^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/asyncssh/connection.py", line 450, in _connect
    await options.waiter
asyncssh.misc.PermissionDenied: Permission denied for user admin on host 192.168.2.62

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 416, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/wattbox/__init__.py", line 98, in async_setup
    wattbox = await async_create_ip_wattbox(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pywattbox/ip_wattbox.py", line 318, in async_create_ip_wattbox
    return await _async_create_wattbox(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pywattbox/base.py", line 110, in _async_create_wattbox
    await wattbox.async_get_initial()
  File "/usr/local/lib/python3.12/site-packages/pywattbox/ip_wattbox.py", line 204, in async_get_initial
    *(await self.async_send_requests(INITIAL_REQUESTS))
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pywattbox/ip_wattbox.py", line 174, in async_send_requests
    await self.async_driver._send_command(
  File "/usr/local/lib/python3.12/site-packages/scrapli/decorators.py", line 282, in decorate
    result = await wrapped_func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pywattbox/driver/async_driver.py", line 108, in _send_command
    await self._open()
  File "/usr/local/lib/python3.12/site-packages/pywattbox/driver/async_driver.py", line 88, in _open
    await self.open()
  File "/usr/local/lib/python3.12/site-packages/scrapli/driver/base/async_driver.py", line 100, in open
    await self.transport.open()
  File "/usr/local/lib/python3.12/site-packages/scrapli/transport/plugins/asyncssh/transport.py", line 202, in open
    raise ScrapliAuthenticationFailed(msg) from exc
scrapli.exceptions.ScrapliAuthenticationFailed: all authentication methods failed
```

For port 23 v0.8.2 , I get this:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 716, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 468, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 463, in _make_request
    httplib_response = conn.getresponse()
                       ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 1428, in getresponse
    response.begin()
  File "/usr/local/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 313, in _read_status
    raise BadStatusLine(line)
http.client.BadStatusLine: Please Login to Continue


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 802, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/util/retry.py", line 552, in increment
    raise six.reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 716, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 468, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 463, in _make_request
    httplib_response = conn.getresponse()
                       ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 1428, in getresponse
    response.begin()
  File "/usr/local/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 313, in _read_status
    raise BadStatusLine(line)
urllib3.exceptions.ProtocolError: ('Connection aborted.', BadStatusLine('Please Login to Continue\n'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 416, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/wattbox/__init__.py", line 97, in async_setup
    hass.data[DOMAIN_DATA][name] = await hass.async_add_executor_job(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pywattbox/wattbox.py", line 56, in __init__
    result = requests.get(
             ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/adapters.py", line 682, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine('Please Login to Continue\n'))
```

And port 23 on v0.9.0b5 gave this:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/asyncio/tasks.py", line 520, in wait_for
    return await fut
           ^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/scrapli/transport/plugins/asynctelnet/transport.py", line 213, in read
    await self._read()
  File "/usr/local/lib/python3.12/site-packages/scrapli/transport/plugins/asynctelnet/transport.py", line 195, in _read
    buf = await self.stdout.read(n)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/streams.py", line 713, in read
    await self._wait_for_data('read')
  File "/usr/local/lib/python3.12/asyncio/streams.py", line 545, in _wait_for_data
    await self._waiter
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/scrapli/decorators.py", line 199, in decorate
    return await asyncio.wait_for(wrapped_func(*args, **kwargs), timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/tasks.py", line 519, in wait_for
    async with timeouts.timeout(timeout):
  File "/usr/local/lib/python3.12/asyncio/timeouts.py", line 115, in __aexit__
    raise TimeoutError from exc_val
TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 416, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/wattbox/__init__.py", line 98, in async_setup
    wattbox = await async_create_ip_wattbox(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pywattbox/ip_wattbox.py", line 318, in async_create_ip_wattbox
    return await _async_create_wattbox(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pywattbox/base.py", line 110, in _async_create_wattbox
    await wattbox.async_get_initial()
  File "/usr/local/lib/python3.12/site-packages/pywattbox/ip_wattbox.py", line 204, in async_get_initial
    *(await self.async_send_requests(INITIAL_REQUESTS))
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pywattbox/ip_wattbox.py", line 174, in async_send_requests
    await self.async_driver._send_command(
  File "/usr/local/lib/python3.12/site-packages/scrapli/decorators.py", line 282, in decorate
    result = await wrapped_func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pywattbox/driver/async_driver.py", line 108, in _send_command
    await self._open()
  File "/usr/local/lib/python3.12/site-packages/pywattbox/driver/async_driver.py", line 88, in _open
    await self.open()
  File "/usr/local/lib/python3.12/site-packages/scrapli/driver/base/async_driver.py", line 109, in open
    await self.on_open(self)
  File "/usr/local/lib/python3.12/site-packages/pywattbox/driver/async_driver.py", line 20, in on_open
    await driver.channel._read_until_prompt()
  File "/usr/local/lib/python3.12/site-packages/scrapli/channel/async_channel.py", line 146, in _read_until_prompt
    b = await self.read()
        ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/scrapli/channel/async_channel.py", line 71, in read
    buf = await self.transport.read()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/scrapli/decorators.py", line 201, in decorate
    _handle_timeout(
  File "/usr/local/lib/python3.12/site-packages/scrapli/decorators.py", line 142, in _handle_timeout
    raise ScrapliTimeout(message)
scrapli.exceptions.ScrapliTimeout: timed out reading from transport
```

**Comment by zacs** [comment]
@kernelpanic85 try using the `develop` branch with port 22 specified. Worked for me at least.

**Comment by zacs** [comment]
Might be possible with HACS. I just add it manually to the `custom_components` folder and it doesn't interfere with HACS (you obviously would need to uninstall the HACS version of wattbox). I believe it is up to @eseglem to decide when things have firmed up enough to cut a new release on main branch :)

**Comment by jes1417** [comment]
HACS moved the option for selecting beta releases to a switch under Devices
and Services for HACS.
