### ISSUE TITLE
Error during setup of component wattbox

### ISSUE THREAD

**Issue by sheyman1** [eseglem/hass-wattbox#9]
## Configuration

wattbox:
- host: 10.10.10.204
  username: !secret wattbox_username
  password: !secret wattbox_password
  name: Wattbox

Add your logs here.

2022-08-07 11:00:05.712 ERROR (MainThread) [homeassistant.setup] Error during setup of component wattbox
File "/config/custom_components/wattbox/__init__.py", line 94, in async_setup
File "/usr/local/lib/python3.10/site-packages/pywattbox/wattbox.py", line 76, in __init__
File "/usr/local/lib/python3.10/site-packages/pywattbox/wattbox.py", line 135, in update

## Describe the bug

Wattbox addon not loading at all.

## Debug log

2022-08-07 11:05:45.165 INFO (MainThread) [homeassistant.setup] Setting up wattbox
2022-08-07 11:05:45.166 INFO (MainThread) [custom_components.wattbox]
wattbox
https://github.com/eseglem/hass-wattbox/issues
2022-08-07 11:05:45.593 ERROR (MainThread) [homeassistant.setup] Error during setup of component wattbox
File "/config/custom_components/wattbox/__init__.py", line 94, in async_setup
File "/usr/local/lib/python3.10/site-packages/pywattbox/wattbox.py", line 76, in __init__
File "/usr/local/lib/python3.10/site-packages/pywattbox/wattbox.py", line 135, in update
- [wattbox](https://github.com/eseglem/hass-wattbox) ([Show logs](/config/logs?filter=wattbox))
2022-08-07 11:05:45.600 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection] [140618375077200] Sending {"id":2,"type":"event","event":{"a":{"persistent_notification.invalid_config":{"s":"notifying","a":{"message":"The following integrations and platforms could not be set up:\n\n - [wattbox](https://github.com/eseglem/hass-wattbox) ([Show logs](/config/logs?filter=wattbox))\n\nPlease check your config and [logs](/config/logs).","title":"Invalid config","friendly_name":"Invalid config"},"c":"01G9WQQZQT16WEGNZ1ZHY4GVAA","lc":1659895545.594447}}}}
2022-08-07 11:05:45.663 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection] [140618375077200] Sending {"id":41,"type":"result","success":true,"result":[{"notification_id":"invalid_config","message":"The following integrations and platforms could not be set up:\n\n - [wattbox](https://github.com/eseglem/hass-wattbox) ([Show logs](/config/logs?filter=wattbox))\n\nPlease check your config and [logs](/config/logs).","status":"unread","title":"Invalid config","created_at":"2022-08-07T18:05:45.594761+00:00"}]}

Add your logs here.

Logger: homeassistant.setup
Source: custom_components/wattbox/__init__.py:94
Integration: wattbox ([documentation](https://github.com/eseglem/hass-wattbox), [issues](https://github.com/eseglem/hass-wattbox/issues))
First occurred: 11:31:33 AM (1 occurrences)
Last logged: 11:31:33 AM

Error during setup of component wattbox
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 235, in _async_setup_component
    result = await task
  File "/config/custom_components/wattbox/__init__.py", line 94, in async_setup
    hass.data[DOMAIN_DATA][name] = await hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/pywattbox/wattbox.py", line 76, in __init__
    self.update()
  File "/usr/local/lib/python3.10/site-packages/pywattbox/wattbox.py", line 135, in update
    self.outlets[i].method = outlet_methods[i - 1]
IndexError: list index out of range

**Comment by eseglem** [comment]
What model wattbox are you connecting to? I only have the WB-700CH-IPV-12 so its the only one I can test against. Everything else is guess work. 

If you can go to `http://10.10.10.204/wattbox_info.xml` in your browser and share that xml with me that would probably be the easiest way for me to solve the issue.

**Comment by sheyman1** [comment]
> What model wattbox are you connecting to? I only have the WB-700CH-IPV-12 so its the only one I can test against. Everything else is guess work.
> 
> If you can go to `http://10.10.10.204/wattbox_info.xml` in your browser and share that xml with me that would probably be the easiest way for me to solve the issue.

Thank you so much for getting back to me, sorry I just saw your reply.  Here is the data you asked for.  Thank you very much for you help.

<request>
<host_name>WattBox</host_name>
<hardware_version>WB-600-IPVCE-12</hardware_version>
<serial_number>2432732367</serial_number>
<site_ip>142.251.46.196,13.107.22.200,151.101.130.114,10.10.10.1,0,0,0,0,0,0</site_ip>
<connect_status>10,40,10,1,-1,-1,-1,-1,-1,-1</connect_status>
<site_lost>0,0,0,0,0,0,0,0,0,0</site_lost>
<auto_reboot>0</auto_reboot>
<outlet_name>Outlet1,Peplink,Outlet3,Tesla Gateway,Outlet5,Outlet6,Sonos Port living room,Outlet8</outlet_name>
<outlet_status>1,0,1,1,1,1,1,1</outlet_status>
<outlet_method>1,1,1,1,1,1,1,1</outlet_method>
<led_status>1,1,0,1</led_status>
<safe_voltage_control>1</safe_voltage_control>
<voltage_value>1224</voltage_value>
<current_value>2</current_value>
<power_value>29</power_value>
<voltage_status>0</voltage_status>
</request>

**Comment by sheyman1** [comment]
Thank you so much for getting back to me, sorry I just saw your reply. Here is the data you asked for. Thank you very much for you help.

[wattbox_info.txt](https://github.com/eseglem/hass-wattbox/files/9377750/wattbox_info.txt)

**Comment by sheyman1** [comment]
My Wattbox unit looks almost the same as yours but maybe the config is different?  Thanks for your help!!!

**Comment by eseglem** [comment]
Sorry, meant to reply over the weekend but got caught up in other things. I see what the issue is, just need to make some updates. I naively assumed that a model ending in `-12` would have 12 programmable plugs, which apparently isn't the case. Yours only has 8 programmable with 4 more that are always on and provide no info in the API. So when it tries to update the 9th plug it breaks. Shouldn't be hard to fix, just need to find the time. 

Need to do something different here: https://github.com/eseglem/pywattbox/blob/master/pywattbox/wattbox.py#L68

**Comment by sheyman1** [comment]
No problem at all, totally understand.  You are correct mine has 4 always on and 8 programmable.  So glad you were able to spot the issue.  Whenever you get a chance and find the time I really appreciate you helping out with getting this to work!!!

**Comment by sheyman1** [comment]
> Sorry, meant to reply over the weekend but got caught up in other things. I see what the issue is, just need to make some updates. I naively assumed that a model ending in `-12` would have 12 programmable plugs, which apparently isn't the case. Yours only has 8 programmable with 4 more that are always on and provide no info in the API. So when it tries to update the 9th plug it breaks. Shouldn't be hard to fix, just need to find the time.
> 
> Need to do something different here: https://github.com/eseglem/pywattbox/blob/master/pywattbox/wattbox.py#L68

Thanks for your help on this when you get time, really appreciate it.

**Comment by eseglem** [comment]
Sorry for the delay. Fix should be up in v0.8.0, try that out and see how it does. 

You can re-open the issue if its still causing problems for you.

**Comment by sheyman1** [comment]
> Sorry for the delay. Fix should be up in v0.8.0, try that out and see how it does.
> 
> You can re-open the issue if its still causing problems for you.

Eseglem:
Works perfectly!!!  Thank you so much for getting this resolved!!!  Love it
Scott
